/*
 * The code in this file is automatically generated @ 2023-12-14 12:51:53.955362.
 * Manual changes to this file will be removed when this file is regenerated.
 */
CREATE SCHEMA [orders];
GO


CREATE TABLE [orders].[Customer] (
  [id] uniqueidentifier NOT NULL
, [address] nvarchar(255) NULL
, CONSTRAINT [pk_Customer]
    PRIMARY KEY (
      [id]
    )
)
;
GO

CREATE TABLE [orders].[Product] (
  [id] uniqueidentifier NOT NULL
, [description] nvarchar(255) NULL
, CONSTRAINT [pk_Product]
    PRIMARY KEY (
      [id]
    )
)
;
GO

CREATE TABLE [orders].[Order] (
  [id] uniqueidentifier NOT NULL
, [orderTimestamp_utc] datetime2 NULL
, [amount] int NULL
, [orderedBy_Customer_id] uniqueidentifier NOT NULL
, [orderFor_Product_id] uniqueidentifier NOT NULL
, CONSTRAINT [pk_Order]
    PRIMARY KEY (
      [id]
    )
)
;
GO

ALTER TABLE [orders].[Order]
ADD
  CONSTRAINT [fk_orderedBy_Customer]
    FOREIGN KEY 
      ([orderedBy_Customer_id])
    REFERENCES [orders].[Customer] 
      ([id])
, CONSTRAINT [fk_orderFor_Product]
    FOREIGN KEY 
      ([orderFor_Product_id])
    REFERENCES [orders].[Product] 
      ([id])
;
GO

CREATE SCHEMA [orders_hda];
GO


CREATE TABLE [orders_hda].[Customer] (
  [hda_validFrom_utc] datetime2 NOT NULL
, [hda_voided] bit NOT NULL
, [id] uniqueidentifier NOT NULL
, [address] nvarchar(255) NULL
, CONSTRAINT [pk_Customer]
    PRIMARY KEY (
      [id]
    , [hda_validFrom_utc]
    )
)
;
GO

CREATE TABLE [orders_hda].[Product] (
  [hda_validFrom_utc] datetime2 NOT NULL
, [hda_voided] bit NOT NULL
, [id] uniqueidentifier NOT NULL
, [description] nvarchar(255) NULL
, CONSTRAINT [pk_Product]
    PRIMARY KEY (
      [id]
    , [hda_validFrom_utc]
    )
)
;
GO

CREATE TABLE [orders_hda].[Order] (
  [hda_validFrom_utc] datetime2 NOT NULL
, [hda_voided] bit NOT NULL
, [id] uniqueidentifier NOT NULL
, [orderTimestamp_utc] datetime2 NULL
, [amount] int NULL
, [orderedBy_Customer_id] uniqueidentifier NULL
, [orderFor_Product_id] uniqueidentifier NULL
, CONSTRAINT [pk_Order]
    PRIMARY KEY (
      [id]
    , [hda_validFrom_utc]
    )
)
;
GO

-- Create PIT function for [orders_hda].[Customer]
CREATE OR ALTER FUNCTION [orders_hda].[ufn_pit_Customer] (
  @timestamp_utc datetime2
)
RETURNS TABLE
AS
RETURN (
  SELECT
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [address]
  FROM
    [orders_hda].[Customer] AS [d]
  WHERE
    [d].[hda_validFrom_utc] <= @timestamp_utc
  AND
    [d].[hda_voided] = 0
  AND
    [hda_validFrom_utc] = (
      SELECT 
        MAX([hda_validFrom_utc])
      FROM 
        [orders_hda].[Customer] AS [h]
      WHERE
        [d].[id] = [h].[id]
      AND
        [h].[hda_validFrom_utc] <= @timestamp_utc  
    )
)
;
GO

-- Create PIT function for [orders_hda].[Product]
CREATE OR ALTER FUNCTION [orders_hda].[ufn_pit_Product] (
  @timestamp_utc datetime2
)
RETURNS TABLE
AS
RETURN (
  SELECT
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [description]
  FROM
    [orders_hda].[Product] AS [d]
  WHERE
    [d].[hda_validFrom_utc] <= @timestamp_utc
  AND
    [d].[hda_voided] = 0
  AND
    [hda_validFrom_utc] = (
      SELECT 
        MAX([hda_validFrom_utc])
      FROM 
        [orders_hda].[Product] AS [h]
      WHERE
        [d].[id] = [h].[id]
      AND
        [h].[hda_validFrom_utc] <= @timestamp_utc  
    )
)
;
GO

-- Create PIT function for [orders_hda].[Order]
CREATE OR ALTER FUNCTION [orders_hda].[ufn_pit_Order] (
  @timestamp_utc datetime2
)
RETURNS TABLE
AS
RETURN (
  SELECT
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [orderTimestamp_utc]
  , [amount]
  , [orderedBy_Customer_id]
  , [orderFor_Product_id]
  FROM
    [orders_hda].[Order] AS [d]
  WHERE
    [d].[hda_validFrom_utc] <= @timestamp_utc
  AND
    [d].[hda_voided] = 0
  AND
    [hda_validFrom_utc] = (
      SELECT 
        MAX([hda_validFrom_utc])
      FROM 
        [orders_hda].[Order] AS [h]
      WHERE
        [d].[id] = [h].[id]
      AND
        [h].[hda_validFrom_utc] <= @timestamp_utc  
    )
)
;
GO

-- Load table [orders_hda].[Customer]
CREATE OR ALTER PROCEDURE [orders_hda].[usp_load_Customer] (
  @timestamp_utc datetime2
)
AS
BEGIN
  -- Load HDA table with changes from source table.
  INSERT INTO [orders_hda].[Customer] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [address]
  )
  SELECT
    @timestamp_utc
  , 0
  , [id]
  , [address]
  FROM 
    [orders].[Customer] AS [src]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders_hda].[ufn_pit_Customer](@timestamp_utc) AS [hda]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]      
    AND 
      ([src].[address] = [hda].[address]
       OR ([src].[address] IS NULL AND [hda].[address] IS NULL)) 
    
  )
  ;

  -- Add records to the HDA table for deleted source records.
  INSERT INTO [orders_hda].[Customer] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  )
  SELECT
    @timestamp_utc
  , 1
  , [id]
  FROM 
    [orders_hda].[ufn_pit_Customer](@timestamp_utc) AS [hda]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders].[Customer] AS [src]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]
  )
  ;
END
;
GO

-- Load table [orders_hda].[Product]
CREATE OR ALTER PROCEDURE [orders_hda].[usp_load_Product] (
  @timestamp_utc datetime2
)
AS
BEGIN
  -- Load HDA table with changes from source table.
  INSERT INTO [orders_hda].[Product] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [description]
  )
  SELECT
    @timestamp_utc
  , 0
  , [id]
  , [description]
  FROM 
    [orders].[Product] AS [src]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders_hda].[ufn_pit_Product](@timestamp_utc) AS [hda]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]      
    AND 
      ([src].[description] = [hda].[description]
       OR ([src].[description] IS NULL AND [hda].[description] IS NULL)) 
    
  )
  ;

  -- Add records to the HDA table for deleted source records.
  INSERT INTO [orders_hda].[Product] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  )
  SELECT
    @timestamp_utc
  , 1
  , [id]
  FROM 
    [orders_hda].[ufn_pit_Product](@timestamp_utc) AS [hda]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders].[Product] AS [src]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]
  )
  ;
END
;
GO

-- Load table [orders_hda].[Order]
CREATE OR ALTER PROCEDURE [orders_hda].[usp_load_Order] (
  @timestamp_utc datetime2
)
AS
BEGIN
  -- Load HDA table with changes from source table.
  INSERT INTO [orders_hda].[Order] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  , [orderTimestamp_utc]
  , [amount]
  , [orderedBy_Customer_id]
  , [orderFor_Product_id]
  )
  SELECT
    @timestamp_utc
  , 0
  , [id]
  , [orderTimestamp_utc]
  , [amount]
  , [orderedBy_Customer_id]
  , [orderFor_Product_id]
  FROM 
    [orders].[Order] AS [src]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders_hda].[ufn_pit_Order](@timestamp_utc) AS [hda]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]      
    AND 
      ([src].[orderTimestamp_utc] = [hda].[orderTimestamp_utc]
       OR ([src].[orderTimestamp_utc] IS NULL AND [hda].[orderTimestamp_utc] IS NULL)) 
    AND 
      ([src].[amount] = [hda].[amount]
       OR ([src].[amount] IS NULL AND [hda].[amount] IS NULL)) 
    AND 
      ([src].[orderedBy_Customer_id] = [hda].[orderedBy_Customer_id]
       OR ([src].[orderedBy_Customer_id] IS NULL AND [hda].[orderedBy_Customer_id] IS NULL)) 
    AND 
      ([src].[orderFor_Product_id] = [hda].[orderFor_Product_id]
       OR ([src].[orderFor_Product_id] IS NULL AND [hda].[orderFor_Product_id] IS NULL)) 
    
  )
  ;

  -- Add records to the HDA table for deleted source records.
  INSERT INTO [orders_hda].[Order] (
    [hda_validFrom_utc]
  , [hda_voided]
  , [id]
  )
  SELECT
    @timestamp_utc
  , 1
  , [id]
  FROM 
    [orders_hda].[ufn_pit_Order](@timestamp_utc) AS [hda]
  WHERE NOT EXISTS (
    SELECT 
      1
    FROM
      [orders].[Order] AS [src]
    WHERE
      1=1
    AND
      [src].[id] = [hda].[id]
  )
  ;
END
;
GO


INSERT INTO [orders].[Product] (
  [id]
, [description]
) VALUES (
  '11111111-1111-1111-1111-111111111111', 'Red hat'
), (
  '22222222-2222-2222-2222-222222222222', 'Green glasses'
), (
  '33333333-3333-3333-3333-333333333333', 'Blue jeans'
)
;

EXEC [orders_hda].[usp_load_Product] @timestamp_utc = '2023-12-01';

SELECT * FROM [orders].[Product];
SELECT * FROM [orders_hda].[Product];
SELECT * FROM [orders_hda].[ufn_pit_Product]('2023-12-02');

UPDATE
  [orders].[Product]
SET
  [description] = 'Yellow glasses'
WHERE
  [id] = '22222222-2222-2222-2222-222222222222'
;
DELETE FROM
  [orders].[Product]
WHERE
  [id] = '33333333-3333-3333-3333-333333333333'
;

EXEC [orders_hda].[usp_load_Product] @timestamp_utc = '2023-12-05';

SELECT * FROM [orders].[Product];
SELECT * FROM [orders_hda].[Product];
SELECT * FROM [orders_hda].[ufn_pit_Product]('2023-12-06');

UPDATE
  [orders].[Product]
SET
  [description] = 'Chartreuse glasses'
WHERE
  [id] = '22222222-2222-2222-2222-222222222222'
;
INSERT INTO [orders].[Product] (
  [id]
, [description]
) VALUES (
  '33333333-3333-3333-3333-333333333333', 'Blue jeans'
);

EXEC [orders_hda].[usp_load_Product] @timestamp_utc = '2023-12-09';

SELECT * FROM [orders].[Product];
SELECT * FROM [orders_hda].[Product];
SELECT * FROM [orders_hda].[ufn_pit_Product]('2023-12-10');
              
IF EXISTS(SELECT 1 FROM [sys].[tables] WHERE [name] = 'Order' AND [schema_id] = SCHEMA_ID('orders'))
BEGIN
  ALTER TABLE [orders].[Order] DROP CONSTRAINT [fk_orderedBy_Customer];
  ALTER TABLE [orders].[Order] DROP CONSTRAINT [fk_orderFor_Product];
END;
GO
DROP TABLE IF EXISTS [orders].[Customer];
GO
DROP TABLE IF EXISTS [orders].[Product];
GO
DROP TABLE IF EXISTS [orders].[Order];
GO
DROP SCHEMA IF EXISTS [orders];
GO
DROP PROCEDURE IF EXISTS [orders_hda].[usp_load_Customer];
GO
DROP FUNCTION IF EXISTS [orders_hda].[ufn_pit_Customer];
GO
DROP TABLE IF EXISTS [orders_hda].[Customer];
GO
DROP PROCEDURE IF EXISTS [orders_hda].[usp_load_Product];
GO
DROP FUNCTION IF EXISTS [orders_hda].[ufn_pit_Product];
GO
DROP TABLE IF EXISTS [orders_hda].[Product];
GO
DROP PROCEDURE IF EXISTS [orders_hda].[usp_load_Order];
GO
DROP FUNCTION IF EXISTS [orders_hda].[ufn_pit_Order];
GO
DROP TABLE IF EXISTS [orders_hda].[Order];
GO
DROP SCHEMA IF EXISTS [orders_hda];
GO
